import { randomInt } from "crypto";

const mockTokens = [
	{
		id: "1",
		name: "2026",
		shortAddress: "8Zwu...pump",
		image:
			"https://res.cloudinary.com/maheshn18/image/upload/v1744041032/profile/pics/hpk2yvnkmxjhwa7jz7jl.jpg",
		pumpProgress: 82,
		marketCap: "$4.21K",
		volume: "$1K",
		liquidity: "0.04 SOL",
		age: "3s",
		txCount: 18,
		txBuyPct: 76,
		txSellPct: 24,
		holders: 5,
		proTraders: 2,
		score: 0,
		views: 1,
		quickBuyAmount: "0 SOL",
	},
	{
		id: "2",
		name: "SMOKE",
		shortAddress: "Aavr...pump",
		image:
			"https://res.cloudinary.com/maheshn18/image/upload/v1744042783/default_ia15jm.png",
		pumpProgress: 64,
		marketCap: "$3.9K",
		volume: "$646",
		liquidity: "0.014 SOL",
		age: "11s",
		txCount: 4,
		txBuyPct: 67,
		txSellPct: 33,
		holders: 1,
		proTraders: 0,
		score: 0,
		views: 3,
		quickBuyAmount: "0 SOL",
	},
	{
		id: "3",
		name: "GAUNTLET",
		shortAddress: "C9UX...pump",
		image:
			"https://res.cloudinary.com/maheshn18/image/upload/v1748600882/t10_qbthk5.jpg",
		pumpProgress: 91,
		marketCap: "$6.8K",
		volume: "$2.3K",
		liquidity: "0.21 SOL",
		age: "12m",
		txCount: 103,
		txBuyPct: 43,
		txSellPct: 57,
		holders: 0,
		proTraders: 0,
		score: 1,
		views: 8,
		quickBuyAmount: "0 SOL",
	},
	{
		id: "4",
		name: "ORBIT",
		shortAddress: "9xAb...pump",
		image:
			"https://res.cloudinary.com/maheshn18/image/upload/v1767295249/crypto.com_sfcegr.webp",
		pumpProgress: 48,
		marketCap: "$1.2K",
		volume: "$410",
		liquidity: "0.008 SOL",
		age: "42s",
		txCount: 9,
		txBuyPct: 55,
		txSellPct: 45,
		holders: 3,
		proTraders: 1,
		score: 0,
		views: 12,
		quickBuyAmount: "0 SOL",
	},
	{
		id: "5",
		name: "NOVA",
		shortAddress: "7QaL...pump",
		image:
			"https://res.cloudinary.com/maheshn18/image/upload/v1767295270/ten_pvozvs.webp",
		pumpProgress: 73,
		marketCap: "$5.4K",
		volume: "$1.9K",
		liquidity: "0.09 SOL",
		age: "1m",
		txCount: 34,
		txBuyPct: 61,
		txSellPct: 39,
		holders: 12,
		proTraders: 4,
		score: 1,
		views: 22,
		quickBuyAmount: "0 SOL",
	},
	{
		id: "6",
		name: "FROST",
		shortAddress: "4ZPt...pump",
		image:
			"https://res.cloudinary.com/maheshn18/image/upload/v1767295293/gauntlet_jeymkt.webp",
		pumpProgress: 29,
		marketCap: "$780",
		volume: "$120",
		liquidity: "0.003 SOL",
		age: "2m",
		txCount: 6,
		txBuyPct: 50,
		txSellPct: 50,
		holders: 2,
		proTraders: 0,
		score: 0,
		views: 4,
		quickBuyAmount: "0 SOL",
	},
	{
		id: "7",
		name: "BLAZE",
		shortAddress: "Lp91...pump",
		image:
			"https://res.cloudinary.com/maheshn18/image/upload/v1767295299/smoke_rsusr6.webp",
		pumpProgress: 88,
		marketCap: "$9.1K",
		volume: "$3.8K",
		liquidity: "0.32 SOL",
		age: "4m",
		txCount: 89,
		txBuyPct: 72,
		txSellPct: 28,
		holders: 24,
		proTraders: 7,
		score: 2,
		views: 64,
		quickBuyAmount: "0 SOL",
	},
	{
		id: "8",
		name: "DUST",
		shortAddress: "D5kP...pump",
		image:
			"https://res.cloudinary.com/maheshn18/image/upload/v1767295244/twelve_q1fzw4.webp",
		pumpProgress: 21,
		marketCap: "$510",
		volume: "$80",
		liquidity: "0.001 SOL",
		age: "5m",
		txCount: 3,
		txBuyPct: 33,
		txSellPct: 67,
		holders: 1,
		proTraders: 0,
		score: 0,
		views: 0,
		quickBuyAmount: "0 SOL",
	},
	{
		id: "9",
		name: "ION",
		shortAddress: "I0nX...pump",
		image:
			"https://res.cloudinary.com/maheshn18/image/upload/v1767295245/coinbase_eftznb.webp",
		pumpProgress: 56,
		marketCap: "$2.9K",
		volume: "$940",
		liquidity: "0.05 SOL",
		age: "7m",
		txCount: 21,
		txBuyPct: 58,
		txSellPct: 42,
		holders: 6,
		proTraders: 1,
		score: 0,
		views: 14,
		quickBuyAmount: "0 SOL",
	},
	{
		id: "10",
		name: "PULSE",
		shortAddress: "PuLs...pump",
		image:
			"https://res.cloudinary.com/maheshn18/image/upload/v1767295250/eight_ddi0us.webp",
		pumpProgress: 95,
		marketCap: "$12.4K",
		volume: "$5.7K",
		liquidity: "0.44 SOL",
		age: "9m",
		txCount: 142,
		txBuyPct: 68,
		txSellPct: 32,
		holders: 48,
		proTraders: 12,
		score: 3,
		views: 96,
		quickBuyAmount: "0 SOL",
	},
	{
		id: "11",
		name: "VOID",
		shortAddress: "Vo1d...pump",
		image:
			"https://res.cloudinary.com/maheshn18/image/upload/v1767295255/five_rgnviu.webp",
		pumpProgress: 37,
		marketCap: "$1.6K",
		volume: "$330",
		liquidity: "0.02 SOL",
		age: "13m",
		txCount: 11,
		txBuyPct: 45,
		txSellPct: 55,
		holders: 4,
		proTraders: 0,
		score: 0,
		views: 7,
		quickBuyAmount: "0 SOL",
	},
	{
		id: "12",
		name: "SPARK",
		shortAddress: "Sp4r...pump",
		image:
			"https://res.cloudinary.com/maheshn18/image/upload/v1767295259/moonpay_e9u5d3.webp",
		pumpProgress: 69,
		marketCap: "$4.7K",
		volume: "$1.4K",
		liquidity: "0.11 SOL",
		age: "18m",
		txCount: 29,
		txBuyPct: 63,
		txSellPct: 37,
		holders: 9,
		proTraders: 2,
		score: 1,
		views: 31,
		quickBuyAmount: "0 SOL",
	},
	{
		id: "13",
		name: "ECHO",
		shortAddress: "EcHo...pump",
		image:
			"https://res.cloudinary.com/maheshn18/image/upload/v1767295262/nine_jieb87.webp",
		pumpProgress: 52,
		marketCap: "$2.2K",
		volume: "$710",
		liquidity: "0.06 SOL",
		age: "23m",
		txCount: 17,
		txBuyPct: 59,
		txSellPct: 41,
		holders: 6,
		proTraders: 1,
		score: 0,
		views: 19,
		quickBuyAmount: "0 SOL",
	},
	{
		id: "14",
		name: "FLUX",
		shortAddress: "FlUx...pump",
		image:
			"https://res.cloudinary.com/maheshn18/image/upload/v1767295266/six_ggw1fp.webp",
		pumpProgress: 77,
		marketCap: "$7.3K",
		volume: "$2.6K",
		liquidity: "0.19 SOL",
		age: "31m",
		txCount: 47,
		txBuyPct: 66,
		txSellPct: 34,
		holders: 17,
		proTraders: 5,
		score: 2,
		views: 53,
		quickBuyAmount: "0 SOL",
	},
	{
		id: "15",
		name: "NEBULA",
		shortAddress: "NeBu...pump",
		image:
			"https://res.cloudinary.com/maheshn18/image/upload/v1767295266/six_ggw1fp.webp",
		pumpProgress: 84,
		marketCap: "$10.1K",
		volume: "$4.1K",
		liquidity: "0.37 SOL",
		age: "44m",
		txCount: 92,
		txBuyPct: 70,
		txSellPct: 30,
		holders: 33,
		proTraders: 9,
		score: 3,
		views: 71,
		quickBuyAmount: "0 SOL",
	},
];

export function generateTokens() {
	return mockTokens;
}

export let tokens = [...mockTokens];

export function mutateTokens() {
	tokens = tokens.map((t) => {
		if (Math.random() < 0.3) {
			return {
				...t,
				marketCap: `$${(Math.random() * 12).toFixed(2)}K`,
				volume: `$${(Math.random() * 6).toFixed(2)}K`,
				txCount: t.txCount + randomInt(0, 3),
				views: t.views + randomInt(0, 2),
			};
		}
		return t;
	});
}
